### ISSUE TITLE
Correcting the CSS file links in bot.html , mobile.html and webdesign.html

### ISSUE THREAD

**Issue by KanishkDadhich** [The-Neon-Dev/website#13]
Hey @The-Neon-Dev . I've seen that the path of the CSS files in the 3 files :- 
1. bot.html
2. mobile.html
3. webdesign.html 
are not correctly added. Hence the CSS is not rendering properly.

I would like to work on this issue
Thanks :)

**Comment by The-Neon-Dev** [comment]
OK
